// Code generated by ForestHub Code Generator
#include <Arduino.h>

#include "workflow_logic.hpp"
#include "env.hpp"
#include "foresthub/platform/platform.hpp"

static std::shared_ptr<foresthub::platform::PlatformContext> platform;

void setup() {
    foresthub::platform::PlatformConfig config;
    config.network.ssid = kWifiSsid;
    config.network.password = kWifiPassword;
    platform = foresthub::platform::CreatePlatform(config);

    platform->console->Begin();

    std::string net_err = platform->network->Connect();
    if (!net_err.empty()) {
        platform->console->Printf("[FATAL] Network: %s\n", net_err.c_str());
        while (true) { platform->time->Delay(1000); }
    }

    std::string time_err = platform->time->SyncTime();
    if (!time_err.empty()) {
        platform->console->Printf("[FATAL] Time: %s\n", time_err.c_str());
        while (true) { platform->time->Delay(1000); }
    }

    WorkflowInit(platform);
}

void loop() {
    WorkflowTick();
}
