// Code generated by ForestHub Code Generator
#ifndef WORKFLOW_LOGIC_HPP
#define WORKFLOW_LOGIC_HPP

#include "foresthub/platform/platform.hpp"

void WorkflowInit(std::shared_ptr<foresthub::platform::PlatformContext> platform);
void WorkflowTick();

#endif // WORKFLOW_LOGIC_HPP
